project:
  type: website

website:
  title: "D1 @ UbiComp 2025"
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cfp.qmd
        text: Call for Papers
      - href: organizers.qmd
        text: Organizers


#<p xmlns:cc="http://creativecommons.org/ns#" >This page is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a></p> 
format:
  html:
    theme: yeti
    css: styles.css
    toc: true

# title-block-banner: banner.png
# include-in-header:
#   - text: |
#       <style>
#       .quarto-title-block .quarto-title-banner {
#         background-position-y: center;
#         height: 500px;
#       }
#       </style>
